const DateDection = require('./date_detection_service')


DateDection.parseDetectedText('BOTTEGA VENETA\nINVITES YOU TO CELEBRATE\nWITH\nCASA DRAGONES\nTHURSDAY, JUNE 14, 2018\n6:00PM-9:OOPM\nBOTTEGA VENETA\n740 MADISON AVENUE\nNEW YORK\nSIGNATURE COCKTAILS BY TEQUILA CASA DRAGONES\nMUSIC BY\nSoo Joo PARK\nRSVP\nEVENTS@US.BOTTEOAVENETA.COM\n')
